import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './Contato.css';
import facebookIcon from '../../assets/img/facebook.png';
import instagramIcon from '../../assets/img/instagram.png';
import twitterIcon from '../../assets/img/facebook.png';
var Contact = function () {
    return (_jsxs("section", { className: "contact-section", children: [_jsxs("div", { className: 'contact-area', children: [_jsx("h2", { children: "Contato" }), _jsxs("div", { className: "social-media", children: [_jsx("h3", { children: "Siga-nos nas redes sociais:" }), _jsxs("div", { className: "social-icons", children: [_jsx("a", { href: "https://www.facebook.com", target: "_blank", rel: "noopener noreferrer", children: _jsx("img", { src: facebookIcon, alt: "Facebook", className: "social-icon" }) }), _jsx("br", {}), _jsx("a", { href: "https://www.instagram.com", target: "_blank", rel: "noopener noreferrer", children: _jsx("img", { src: instagramIcon, alt: "Instagram", className: "social-icon" }) }), _jsx("br", {}), _jsx("a", { href: "https://www.twitter.com", target: "_blank", rel: "noopener noreferrer", children: _jsx("img", { src: twitterIcon, alt: "Twitter", className: "social-icon" }) }), _jsx("br", {}), _jsx("a", { href: "https://www.twitter.com", target: "_blank", rel: "noopener noreferrer", children: _jsx("img", { src: twitterIcon, alt: "Twitter", className: "social-icon" }) })] })] }), _jsx("p", { children: "Se voc\u00EA tiver alguma d\u00FAvida ou precisar de mais informa\u00E7\u00F5es, entre em contato conosco!" }), _jsx("div", { children: _jsxs("form", { className: "contact-form", children: [_jsx("label", { htmlFor: "name", children: "Nome:" }), _jsx("input", { type: "text", id: "name", name: "name", required: true }), _jsx("label", { htmlFor: "phone", children: "Telefone:" }), _jsx("input", { type: "tel", id: "phone", name: "phone", required: true }), _jsx("label", { htmlFor: "message", children: "Mensagem:" }), _jsx("textarea", { id: "message", name: "message", required: true }), _jsx("button", { type: "submit", className: "contact-button-page", children: "Enviar" })] }) })] }), _jsxs("div", { className: "location-section", children: [_jsx("h3", { children: "Endere\u00E7o" }), _jsx("p", { children: "Rua Exemplo, 123 - Bairro, Cidade - Estado, 00000-000" }), _jsx("iframe", { src: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3168.357900924102!2d-122.084!3d37.42199899999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fba4f4e6b7c7d%3A0x800e0c11a6b0e4b6!2sGoogleplex!5e0!3m2!1spt-BR!2sbr!4v1614193908943!5m2!1spt-BR!2sbr", width: "600", height: "450", style: { border: 0 }, allowFullScreen: true, loading: "lazy" })] })] }));
};
export default Contact;
